name: Deploy to VPS  

on:  
  push:  
    branches:  
      - master

jobs:  
  deploy:  
    runs-on: ubuntu-latest  

    steps:  
      - name: Checkout code  
        uses: actions/checkout@v2  

      - name: Set up Node.js  
        uses: actions/setup-node@v2  
        with:  
          node-version: '23'

      - name: Install dependencies  
        run: npm install  

      - name: Run Build  
        run: npm run build  

      - name: Deploy to VPS  
        env:  
          VPS_USERNAME: ${{ secrets.VPS_USERNAME }}  
          VPS_HOST: ${{ secrets.VPS_HOST }}  
          VPS_SSH_KEY: ${{ secrets.VPS_SSH_KEY }}  
        run: |  
          echo "$VPS_SSH_KEY" > private_key  
          chmod 600 private_key  
          scp -o StrictHostKeyChecking=no -i private_key -r ./* "$VPS_USERNAME@$VPS_HOST:/home/finance/frontend"  
          ssh -o StrictHostKeyChecking=no -i private_key "$VPS_USERNAME@$VPS_HOST" "bash /home/finance/frontend/deploy.sh"